# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: "3.1.0"
info:
  title: Finances API
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /books:
    get:
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: object
                required:
                  - books
                properties:
                  books:
                    type: array
                    items:
                      $ref: "#/components/schemas/Book"

  /health:
    get:
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: object
                properties:
                  status:
                    $ref: "#/components/schemas/ServerHealthStatus"
                  reason:
                    type: string
                required:
                  - status

components:
  schemas:
    ExistingResource:
      type: object
      required:
        - id
        - created_at
        - updated_at
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Book:
      type: object
      allOf:
        - $ref: "#/components/schemas/ExistingResource"
        - $ref: "#/components/schemas/BookProperties"

    BookProperties:
      type: object
      required:
        - name
        - owner_id
        - default_currency_iso_code
      properties:
        name:
          type: string
        owner_id:
          type: string
        default_currency_iso_code:
          type: string

    ServerHealthStatus:
      type: string
      enum:
        - healthy
        - unhealthy
