package api

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/adeynack/finances/pkg/repository/gen/finances/public/model"
	. "github.com/adeynack/finances/pkg/repository/gen/finances/public/table"
	. "github.com/go-jet/jet/v2/postgres"
	"github.com/samber/lo"
	slogctx "github.com/veqryn/slog-context"
)

func (s *Service) GetBooks(ctx context.Context, request GetBooksRequestObject) (GetBooksResponseObject, error) {
	// `GetBooksRequestObject` is generated, and its content is already filled by
	// the generated code with this request's values.

	// Query (through a repo) the database
	booksFromDB, err := getBooksFromRepo(ctx, s.DB)
	if err != nil {
		return nil, fmt.Errorf("fetching books from database: %w", err)
	}
	slogctx.Info(ctx, fmt.Sprintf("getBooksFromRepo returned %d entries", len(booksFromDB)))

	// Perform data manipulation (if any) and map
	// to the types generated by openapi-codegen.
	booksForAPIResponse := lo.Map(booksFromDB, func(b BooksWithOwner, _ int) Book {
		return Book{
			CreatedAt:              b.CreatedAt,
			DefaultCurrencyIsoCode: b.DefaultCurrencyIsoCode,
			Id:                     b.ID.String(),
			Name:                   b.Name,
			OwnerId:                b.OwnerID.String(),
			OwnerDisplayName:       b.Owner.DisplayName,
			UpdatedAt:              b.UpdatedAt,
		}
	})

	// Return one of the generated type that exist only for this endpoint/handler.
	// One per documented return case is generated (eg: `UpdateBook404JSONResponse`
	// when the book to update does not exist).
	return GetBooks200JSONResponse{Books: booksForAPIResponse}, nil
}

type BooksWithOwner struct {
	model.Books
	Owner model.Users
}

func getBooksFromRepo(ctx context.Context, db *sql.DB) ([]BooksWithOwner, error) {
	stmt := SELECT(
		Books.AllColumns,
		Users.DisplayName,
	).FROM(
		Books.
			INNER_JOIN(Users, Users.ID.EQ(Books.OwnerID)),
	).ORDER_BY(Books.Name)

	var result []BooksWithOwner
	err := stmt.QueryContext(ctx, db, &result)
	if err != nil {
		return nil, err
	}

	return result, nil
}
