openapi: "3.0.4"
components:
  schemas:
    ID:
      type: string
      format: uuid
    ExistingResource:
      type: object
      required:
        - id
        - created_at
        - updated_at
      properties:
        id:
          $ref: "#/components/schemas/ID"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Book:
      type: object
      allOf:
        - $ref: "#/components/schemas/ExistingResource"
        - $ref: "#/components/schemas/BookProperties"
        - type: object
          required:
            - owner_display_name
          properties:
            owner_display_name:
              type: string

    BookProperties:
      type: object
      required:
        - name
        - owner_id
        - default_currency_iso_code
      properties:
        name:
          type: string
        owner_id:
          $ref: "#/components/schemas/ID"
        default_currency_iso_code:
          type: string

    ServerHealthStatus:
      type: string
      enum:
        - healthy
        - unhealthy

    ExchangeStatus:
      type: string
      enum:
        - uncleared
        - reconciling
        - cleared

    ExchangeWithSplits:
      type: object
      allOf:
        - $ref: "#/components/schemas/ExistingResource"
        - $ref: "#/components/schemas/ExchangeProperties"
        - type: object
          required:
            - splits
          properties:
            splits:
              type: array
              items:
                $ref: "#/components/schemas/Split"

    ExchangeProperties:
      type: object
      required:
        - date
        - register_id
        - description
        - status
      properties:
        date:
          type: string
          format: date
        register_id:
          $ref: "#/components/schemas/ID"
        cheque:
          type: string
        description:
          type: string
        memo:
          type: string
        status:
          $ref: "#/components/schemas/ExchangeStatus"

    Split:
      type: object
      allOf:
        - $ref: "#/components/schemas/ExistingResource"
        - $ref: "#/components/schemas/SplitProperties"

    SplitProperties:
      type: object
      required:
        - exchange_id
        - destination_register_id
        - amount
        - status
      properties:
        exchange_id:
          $ref: "#/components/schemas/ID"
        destination_register_id:
          $ref: "#/components/schemas/ID"
        amount:
          type: integer
          x-go-type: int64
        counterpart_amount:
          type: integer
          x-go-type: int64
        memo:
          type: string
        status:
          $ref: "#/components/schemas/ExchangeStatus"
