// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
insert into books(
  created_at,
  updated_at,
  name,
  owner_id,
  default_currency_iso_code
) values (
  $1, -- created_at,
  $2, -- updated_at,
  $3, -- name,
  $4, -- owner_id,
  $5  -- default_currency_iso_code
)
returning id, created_at, updated_at, name, owner_id, default_currency_iso_code
`

type CreateBookParams struct {
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	OwnerID                uuid.UUID
	DefaultCurrencyIsoCode string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.OwnerID,
		arg.DefaultCurrencyIsoCode,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.DefaultCurrencyIsoCode,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
select
  books.id, books.created_at, books.updated_at, books.name, books.owner_id, books.default_currency_iso_code,
  users.display_name as owner_display_name
from books
inner join users on users.id = books.owner_id
where books.id = $1
`

type GetBookByIDRow struct {
	ID                     uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	OwnerID                uuid.UUID
	DefaultCurrencyIsoCode string
	OwnerDisplayName       string
}

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (GetBookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.DefaultCurrencyIsoCode,
		&i.OwnerDisplayName,
	)
	return i, err
}

const getBooks = `-- name: GetBooks :many
select
  books.id, books.created_at, books.updated_at, books.name, books.owner_id, books.default_currency_iso_code,
  users.display_name as owner_display_name
from books
inner join users on users.id = books.owner_id
order by books.name, books.id
`

type GetBooksRow struct {
	ID                     uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	OwnerID                uuid.UUID
	DefaultCurrencyIsoCode string
	OwnerDisplayName       string
}

func (q *Queries) GetBooks(ctx context.Context) ([]GetBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksRow
	for rows.Next() {
		var i GetBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.OwnerID,
			&i.DefaultCurrencyIsoCode,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
