// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchanges.sql

package sqlcdb

import (
	"context"
)

const getExchanges = `-- name: GetExchanges :many
select
  exchanges.id, exchanges.created_at, exchanges.updated_at, exchanges.date, exchanges.register_id, exchanges.cheque, exchanges.description, exchanges.memo, exchanges.status
from
  exchanges
order by
  exchanges.date,
  exchanges.created_at,
  exchanges.id
`

func (q *Queries) GetExchanges(ctx context.Context) ([]Exchange, error) {
	rows, err := q.db.QueryContext(ctx, getExchanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exchange
	for rows.Next() {
		var i Exchange
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Date,
			&i.RegisterID,
			&i.Cheque,
			&i.Description,
			&i.Memo,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
