// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ExchangeStatus string

const (
	ExchangeStatusUncleared   ExchangeStatus = "uncleared"
	ExchangeStatusReconciling ExchangeStatus = "reconciling"
	ExchangeStatusCleared     ExchangeStatus = "cleared"
)

func (e *ExchangeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExchangeStatus(s)
	case string:
		*e = ExchangeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExchangeStatus: %T", src)
	}
	return nil
}

type NullExchangeStatus struct {
	ExchangeStatus ExchangeStatus
	Valid          bool // Valid is true if ExchangeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExchangeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExchangeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExchangeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExchangeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExchangeStatus), nil
}

type RegisterTypes string

const (
	RegisterTypesBank        RegisterTypes = "Bank"
	RegisterTypesCard        RegisterTypes = "Card"
	RegisterTypesInvestment  RegisterTypes = "Investment"
	RegisterTypesAsset       RegisterTypes = "Asset"
	RegisterTypesLiability   RegisterTypes = "Liability"
	RegisterTypesLoan        RegisterTypes = "Loan"
	RegisterTypesInstitution RegisterTypes = "Institution"
	RegisterTypesExpense     RegisterTypes = "Expense"
	RegisterTypesIncome      RegisterTypes = "Income"
)

func (e *RegisterTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegisterTypes(s)
	case string:
		*e = RegisterTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for RegisterTypes: %T", src)
	}
	return nil
}

type NullRegisterTypes struct {
	RegisterTypes RegisterTypes
	Valid         bool // Valid is true if RegisterTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegisterTypes) Scan(value interface{}) error {
	if value == nil {
		ns.RegisterTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegisterTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegisterTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegisterTypes), nil
}

type Book struct {
	ID                     uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	OwnerID                uuid.UUID
	DefaultCurrencyIsoCode string
}

type Exchange struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	// Date the exchange appears in the book.
	Date time.Time
	// From which register does the money come from.
	RegisterID uuid.UUID
	// Cheque information.
	Cheque sql.NullString
	// Label of the exchange.
	Description string
	// Detail about the exchange.
	Memo   sql.NullString
	Status ExchangeStatus
}

type ImportOrigin struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubjectType    string
	SubjectID      uuid.UUID
	ExternalSystem string
	ExternalID     string
}

type Register struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Type      RegisterTypes
	BookID    uuid.UUID
	// A null parent means it is a root register.
	ParentID uuid.NullUUID
	// Opening date of the register.
	StartsAt time.Time
	// Optional expiration date of the register (ex: for a credit card).
	ExpiresAt       sql.NullTime
	CurrencyIsoCode string
	Notes           sql.NullString
	// Balance amount in the account at its creation (typically 0)
	InitialBalance int64
	Active         bool
	// The category automatically selected when entering a new exchange from this register.
	DefaultCategory uuid.NullUUID
	// Name of the institution (ex: bank) managing the registry (ex: credit card).
	InstitutionName sql.NullString
	// account_numberNumber by which the register is referred to (ex: bank account number).
	AccountNumber sql.NullString
	// In the case the register is identified by an International Bank Account Number (IBAN).
	Iban sql.NullString
	// In the case the register is being charged interests, its rate per year (ex: credit card).
	AnnualInterestRate sql.NullString
	// In the case the register has a credit limit (ex: credit card, credit margin).
	CreditLimit sql.NullInt64
	// In the case the register is linked to a card, its number (ex: a credit card).
	CardNumber sql.NullString
}

type Split struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ExchangeID uuid.UUID
	// To which register is the money going to for this split.
	DestinationRegisterID uuid.UUID
	Amount                int64
	// Amount in the destination register, if it differs from 'amount' (ex: an exchange rate applies).
	CounterpartAmount sql.NullInt64
	// Detail about the exchange, to show in the destination register.
	Memo   sql.NullString
	Status ExchangeStatus
}

type User struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Email             string
	EncryptedPassword string
	Admin             bool
	DisplayName       string
}
