// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: splits.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getSplitsForExchangeIds = `-- name: GetSplitsForExchangeIds :many
select
  splits.amount,
  splits.counterpart_amount,
  splits.created_at,
  splits.destination_register_id,
  splits.exchange_id,
  splits.id,
  splits.memo,
  splits.status,
  splits.updated_at
from
  splits
where
  splits.exchange_id = ANY($1::uuid[])
order by
  splits.created_at,
  splits.id
`

type GetSplitsForExchangeIdsRow struct {
	Amount                int64
	CounterpartAmount     sql.NullInt64
	CreatedAt             time.Time
	DestinationRegisterID uuid.UUID
	ExchangeID            uuid.UUID
	ID                    uuid.UUID
	Memo                  sql.NullString
	Status                ExchangeStatus
	UpdatedAt             time.Time
}

func (q *Queries) GetSplitsForExchangeIds(ctx context.Context, dollar_1 []uuid.UUID) ([]GetSplitsForExchangeIdsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsForExchangeIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSplitsForExchangeIdsRow
	for rows.Next() {
		var i GetSplitsForExchangeIdsRow
		if err := rows.Scan(
			&i.Amount,
			&i.CounterpartAmount,
			&i.CreatedAt,
			&i.DestinationRegisterID,
			&i.ExchangeID,
			&i.ID,
			&i.Memo,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
