// Package apimodel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apimodel

import (
	"time"
)

// Defines values for ServerHealthStatus.
const (
	ServerHealthStatusHealthy   ServerHealthStatus = "healthy"
	ServerHealthStatusUnhealthy ServerHealthStatus = "unhealthy"
)

// Book defines model for Book.
type Book struct {
	CreatedAt              time.Time `json:"created_at"`
	DefaultCurrencyIsoCode string    `json:"default_currency_iso_code"`
	Id                     string    `json:"id"`
	Name                   string    `json:"name"`
	OwnerDisplayName       string    `json:"owner_display_name"`
	OwnerId                string    `json:"owner_id"`
	UpdatedAt              time.Time `json:"updated_at"`
}

// BookProperties defines model for BookProperties.
type BookProperties struct {
	DefaultCurrencyIsoCode string `json:"default_currency_iso_code"`
	Name                   string `json:"name"`
	OwnerDisplayName       string `json:"owner_display_name"`
	OwnerId                string `json:"owner_id"`
}

// ExistingResource defines model for ExistingResource.
type ExistingResource struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ServerHealthStatus defines model for ServerHealthStatus.
type ServerHealthStatus string
