// Package apimodel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apimodel

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ExchangeStatus.
const (
	ExchangeStatusCleared     ExchangeStatus = "cleared"
	ExchangeStatusReconciling ExchangeStatus = "reconciling"
	ExchangeStatusUncleared   ExchangeStatus = "uncleared"
)

// Defines values for ServerHealthStatus.
const (
	ServerHealthStatusHealthy   ServerHealthStatus = "healthy"
	ServerHealthStatusUnhealthy ServerHealthStatus = "unhealthy"
)

// Book defines model for Book.
type Book struct {
	CreatedAt              time.Time `json:"created_at"`
	DefaultCurrencyIsoCode string    `json:"default_currency_iso_code"`
	Id                     ID        `json:"id"`
	Name                   string    `json:"name"`
	OwnerDisplayName       string    `json:"owner_display_name"`
	OwnerId                ID        `json:"owner_id"`
	UpdatedAt              time.Time `json:"updated_at"`
}

// BookProperties defines model for BookProperties.
type BookProperties struct {
	DefaultCurrencyIsoCode string `json:"default_currency_iso_code"`
	Name                   string `json:"name"`
	OwnerId                ID     `json:"owner_id"`
}

// ExchangeProperties defines model for ExchangeProperties.
type ExchangeProperties struct {
	Cheque      *string            `json:"cheque,omitempty"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Memo        *string            `json:"memo,omitempty"`
	RegisterId  ID                 `json:"register_id"`
	Status      ExchangeStatus     `json:"status"`
}

// ExchangeStatus defines model for ExchangeStatus.
type ExchangeStatus string

// ExchangeWithSplits defines model for ExchangeWithSplits.
type ExchangeWithSplits struct {
	Cheque      *string            `json:"cheque,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Id          ID                 `json:"id"`
	Memo        *string            `json:"memo,omitempty"`
	RegisterId  ID                 `json:"register_id"`
	Splits      []Split            `json:"splits"`
	Status      ExchangeStatus     `json:"status"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ExistingResource defines model for ExistingResource.
type ExistingResource struct {
	CreatedAt time.Time `json:"created_at"`
	Id        ID        `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// ServerHealthStatus defines model for ServerHealthStatus.
type ServerHealthStatus string

// Split defines model for Split.
type Split struct {
	Amount                int64          `json:"amount"`
	CounterpartAmount     *int64         `json:"counterpart_amount,omitempty"`
	CreatedAt             time.Time      `json:"created_at"`
	DestinationRegisterId ID             `json:"destination_register_id"`
	ExchangeId            ID             `json:"exchange_id"`
	Id                    ID             `json:"id"`
	Memo                  *string        `json:"memo,omitempty"`
	Status                ExchangeStatus `json:"status"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

// SplitProperties defines model for SplitProperties.
type SplitProperties struct {
	Amount                int64          `json:"amount"`
	CounterpartAmount     *int64         `json:"counterpart_amount,omitempty"`
	DestinationRegisterId ID             `json:"destination_register_id"`
	ExchangeId            ID             `json:"exchange_id"`
	Memo                  *string        `json:"memo,omitempty"`
	Status                ExchangeStatus `json:"status"`
}
