// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/adeynack/finances/model"
)

func newExchange(db *gorm.DB, opts ...gen.DOOption) exchange {
	_exchange := exchange{}

	_exchange.exchangeDo.UseDB(db, opts...)
	_exchange.exchangeDo.UseModel(&model.Exchange{})

	tableName := _exchange.exchangeDo.TableName()
	_exchange.ALL = field.NewAsterisk(tableName)
	_exchange.ID = field.NewString(tableName, "id")
	_exchange.CreatedAt = field.NewField(tableName, "created_at")
	_exchange.UpdatedAt = field.NewField(tableName, "updated_at")
	_exchange.Date = field.NewTime(tableName, "date")
	_exchange.RegisterID = field.NewString(tableName, "register_id")
	_exchange.Cheque = field.NewString(tableName, "cheque")
	_exchange.Description = field.NewString(tableName, "description")
	_exchange.Memo = field.NewString(tableName, "memo")
	_exchange.Status = field.NewString(tableName, "status")
	_exchange.Register = exchangeBelongsToRegister{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Register", "model.Register"),
		Book: struct {
			field.RelationField
			Owner struct {
				field.RelationField
				Books struct {
					field.RelationField
				}
			}
			ImportOrigins struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Register.Book", "model.Book"),
			Owner: struct {
				field.RelationField
				Books struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Register.Book.Owner", "model.User"),
				Books: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Register.Book.Owner.Books", "model.Book"),
				},
			},
			ImportOrigins: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Register.Book.ImportOrigins", "model.ImportOrigin"),
			},
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Register.Parent", "model.Register"),
		},
		DefaultCategory: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Register.DefaultCategory", "model.Register"),
		},
		ImportOrigins: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Register.ImportOrigins", "model.ImportOrigin"),
		},
	}

	_exchange.fillFieldMap()

	return _exchange
}

type exchange struct {
	exchangeDo

	ALL         field.Asterisk
	ID          field.String
	CreatedAt   field.Field
	UpdatedAt   field.Field
	Date        field.Time
	RegisterID  field.String
	Cheque      field.String
	Description field.String
	Memo        field.String
	Status      field.String
	Register    exchangeBelongsToRegister

	fieldMap map[string]field.Expr
}

func (e exchange) Table(newTableName string) *exchange {
	e.exchangeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e exchange) As(alias string) *exchange {
	e.exchangeDo.DO = *(e.exchangeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *exchange) updateTableName(table string) *exchange {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.CreatedAt = field.NewField(table, "created_at")
	e.UpdatedAt = field.NewField(table, "updated_at")
	e.Date = field.NewTime(table, "date")
	e.RegisterID = field.NewString(table, "register_id")
	e.Cheque = field.NewString(table, "cheque")
	e.Description = field.NewString(table, "description")
	e.Memo = field.NewString(table, "memo")
	e.Status = field.NewString(table, "status")

	e.fillFieldMap()

	return e
}

func (e *exchange) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *exchange) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["date"] = e.Date
	e.fieldMap["register_id"] = e.RegisterID
	e.fieldMap["cheque"] = e.Cheque
	e.fieldMap["description"] = e.Description
	e.fieldMap["memo"] = e.Memo
	e.fieldMap["status"] = e.Status

}

func (e exchange) clone(db *gorm.DB) exchange {
	e.exchangeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e exchange) replaceDB(db *gorm.DB) exchange {
	e.exchangeDo.ReplaceDB(db)
	return e
}

type exchangeBelongsToRegister struct {
	db *gorm.DB

	field.RelationField

	Book struct {
		field.RelationField
		Owner struct {
			field.RelationField
			Books struct {
				field.RelationField
			}
		}
		ImportOrigins struct {
			field.RelationField
		}
	}
	Parent struct {
		field.RelationField
	}
	DefaultCategory struct {
		field.RelationField
	}
	ImportOrigins struct {
		field.RelationField
	}
}

func (a exchangeBelongsToRegister) Where(conds ...field.Expr) *exchangeBelongsToRegister {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a exchangeBelongsToRegister) WithContext(ctx context.Context) *exchangeBelongsToRegister {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a exchangeBelongsToRegister) Session(session *gorm.Session) *exchangeBelongsToRegister {
	a.db = a.db.Session(session)
	return &a
}

func (a exchangeBelongsToRegister) Model(m *model.Exchange) *exchangeBelongsToRegisterTx {
	return &exchangeBelongsToRegisterTx{a.db.Model(m).Association(a.Name())}
}

type exchangeBelongsToRegisterTx struct{ tx *gorm.Association }

func (a exchangeBelongsToRegisterTx) Find() (result *model.Register, err error) {
	return result, a.tx.Find(&result)
}

func (a exchangeBelongsToRegisterTx) Append(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a exchangeBelongsToRegisterTx) Replace(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a exchangeBelongsToRegisterTx) Delete(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a exchangeBelongsToRegisterTx) Clear() error {
	return a.tx.Clear()
}

func (a exchangeBelongsToRegisterTx) Count() int64 {
	return a.tx.Count()
}

type exchangeDo struct{ gen.DO }

func (e exchangeDo) Debug() *exchangeDo {
	return e.withDO(e.DO.Debug())
}

func (e exchangeDo) WithContext(ctx context.Context) *exchangeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e exchangeDo) ReadDB() *exchangeDo {
	return e.Clauses(dbresolver.Read)
}

func (e exchangeDo) WriteDB() *exchangeDo {
	return e.Clauses(dbresolver.Write)
}

func (e exchangeDo) Session(config *gorm.Session) *exchangeDo {
	return e.withDO(e.DO.Session(config))
}

func (e exchangeDo) Clauses(conds ...clause.Expression) *exchangeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e exchangeDo) Returning(value interface{}, columns ...string) *exchangeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e exchangeDo) Not(conds ...gen.Condition) *exchangeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e exchangeDo) Or(conds ...gen.Condition) *exchangeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e exchangeDo) Select(conds ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e exchangeDo) Where(conds ...gen.Condition) *exchangeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e exchangeDo) Order(conds ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e exchangeDo) Distinct(cols ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e exchangeDo) Omit(cols ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e exchangeDo) Join(table schema.Tabler, on ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e exchangeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e exchangeDo) RightJoin(table schema.Tabler, on ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e exchangeDo) Group(cols ...field.Expr) *exchangeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e exchangeDo) Having(conds ...gen.Condition) *exchangeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e exchangeDo) Limit(limit int) *exchangeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e exchangeDo) Offset(offset int) *exchangeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e exchangeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *exchangeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e exchangeDo) Unscoped() *exchangeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e exchangeDo) Create(values ...*model.Exchange) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e exchangeDo) CreateInBatches(values []*model.Exchange, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e exchangeDo) Save(values ...*model.Exchange) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e exchangeDo) First() (*model.Exchange, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Exchange), nil
	}
}

func (e exchangeDo) Take() (*model.Exchange, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Exchange), nil
	}
}

func (e exchangeDo) Last() (*model.Exchange, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Exchange), nil
	}
}

func (e exchangeDo) Find() ([]*model.Exchange, error) {
	result, err := e.DO.Find()
	return result.([]*model.Exchange), err
}

func (e exchangeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Exchange, err error) {
	buf := make([]*model.Exchange, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e exchangeDo) FindInBatches(result *[]*model.Exchange, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e exchangeDo) Attrs(attrs ...field.AssignExpr) *exchangeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e exchangeDo) Assign(attrs ...field.AssignExpr) *exchangeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e exchangeDo) Joins(fields ...field.RelationField) *exchangeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e exchangeDo) Preload(fields ...field.RelationField) *exchangeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e exchangeDo) FirstOrInit() (*model.Exchange, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Exchange), nil
	}
}

func (e exchangeDo) FirstOrCreate() (*model.Exchange, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Exchange), nil
	}
}

func (e exchangeDo) FindByPage(offset int, limit int) (result []*model.Exchange, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e exchangeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e exchangeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e exchangeDo) Delete(models ...*model.Exchange) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *exchangeDo) withDO(do gen.Dao) *exchangeDo {
	e.DO = *do.(*gen.DO)
	return e
}
