// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/adeynack/finances/model"
)

func newImportOrigin(db *gorm.DB, opts ...gen.DOOption) importOrigin {
	_importOrigin := importOrigin{}

	_importOrigin.importOriginDo.UseDB(db, opts...)
	_importOrigin.importOriginDo.UseModel(&model.ImportOrigin{})

	tableName := _importOrigin.importOriginDo.TableName()
	_importOrigin.ALL = field.NewAsterisk(tableName)
	_importOrigin.ID = field.NewString(tableName, "id")
	_importOrigin.CreatedAt = field.NewField(tableName, "created_at")
	_importOrigin.UpdatedAt = field.NewField(tableName, "updated_at")
	_importOrigin.SubjectType = field.NewString(tableName, "subject_type")
	_importOrigin.SubjectID = field.NewString(tableName, "subject_id")
	_importOrigin.ExternalSystem = field.NewString(tableName, "external_system")
	_importOrigin.ExternalID = field.NewString(tableName, "external_id")

	_importOrigin.fillFieldMap()

	return _importOrigin
}

type importOrigin struct {
	importOriginDo

	ALL            field.Asterisk
	ID             field.String
	CreatedAt      field.Field
	UpdatedAt      field.Field
	SubjectType    field.String
	SubjectID      field.String
	ExternalSystem field.String
	ExternalID     field.String

	fieldMap map[string]field.Expr
}

func (i importOrigin) Table(newTableName string) *importOrigin {
	i.importOriginDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i importOrigin) As(alias string) *importOrigin {
	i.importOriginDo.DO = *(i.importOriginDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *importOrigin) updateTableName(table string) *importOrigin {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.CreatedAt = field.NewField(table, "created_at")
	i.UpdatedAt = field.NewField(table, "updated_at")
	i.SubjectType = field.NewString(table, "subject_type")
	i.SubjectID = field.NewString(table, "subject_id")
	i.ExternalSystem = field.NewString(table, "external_system")
	i.ExternalID = field.NewString(table, "external_id")

	i.fillFieldMap()

	return i
}

func (i *importOrigin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *importOrigin) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 7)
	i.fieldMap["id"] = i.ID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["subject_type"] = i.SubjectType
	i.fieldMap["subject_id"] = i.SubjectID
	i.fieldMap["external_system"] = i.ExternalSystem
	i.fieldMap["external_id"] = i.ExternalID
}

func (i importOrigin) clone(db *gorm.DB) importOrigin {
	i.importOriginDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i importOrigin) replaceDB(db *gorm.DB) importOrigin {
	i.importOriginDo.ReplaceDB(db)
	return i
}

type importOriginDo struct{ gen.DO }

func (i importOriginDo) Debug() *importOriginDo {
	return i.withDO(i.DO.Debug())
}

func (i importOriginDo) WithContext(ctx context.Context) *importOriginDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i importOriginDo) ReadDB() *importOriginDo {
	return i.Clauses(dbresolver.Read)
}

func (i importOriginDo) WriteDB() *importOriginDo {
	return i.Clauses(dbresolver.Write)
}

func (i importOriginDo) Session(config *gorm.Session) *importOriginDo {
	return i.withDO(i.DO.Session(config))
}

func (i importOriginDo) Clauses(conds ...clause.Expression) *importOriginDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i importOriginDo) Returning(value interface{}, columns ...string) *importOriginDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i importOriginDo) Not(conds ...gen.Condition) *importOriginDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i importOriginDo) Or(conds ...gen.Condition) *importOriginDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i importOriginDo) Select(conds ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i importOriginDo) Where(conds ...gen.Condition) *importOriginDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i importOriginDo) Order(conds ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i importOriginDo) Distinct(cols ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i importOriginDo) Omit(cols ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i importOriginDo) Join(table schema.Tabler, on ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i importOriginDo) LeftJoin(table schema.Tabler, on ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i importOriginDo) RightJoin(table schema.Tabler, on ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i importOriginDo) Group(cols ...field.Expr) *importOriginDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i importOriginDo) Having(conds ...gen.Condition) *importOriginDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i importOriginDo) Limit(limit int) *importOriginDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i importOriginDo) Offset(offset int) *importOriginDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i importOriginDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *importOriginDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i importOriginDo) Unscoped() *importOriginDo {
	return i.withDO(i.DO.Unscoped())
}

func (i importOriginDo) Create(values ...*model.ImportOrigin) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i importOriginDo) CreateInBatches(values []*model.ImportOrigin, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i importOriginDo) Save(values ...*model.ImportOrigin) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i importOriginDo) First() (*model.ImportOrigin, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportOrigin), nil
	}
}

func (i importOriginDo) Take() (*model.ImportOrigin, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportOrigin), nil
	}
}

func (i importOriginDo) Last() (*model.ImportOrigin, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportOrigin), nil
	}
}

func (i importOriginDo) Find() ([]*model.ImportOrigin, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImportOrigin), err
}

func (i importOriginDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImportOrigin, err error) {
	buf := make([]*model.ImportOrigin, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i importOriginDo) FindInBatches(result *[]*model.ImportOrigin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i importOriginDo) Attrs(attrs ...field.AssignExpr) *importOriginDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i importOriginDo) Assign(attrs ...field.AssignExpr) *importOriginDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i importOriginDo) Joins(fields ...field.RelationField) *importOriginDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i importOriginDo) Preload(fields ...field.RelationField) *importOriginDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i importOriginDo) FirstOrInit() (*model.ImportOrigin, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportOrigin), nil
	}
}

func (i importOriginDo) FirstOrCreate() (*model.ImportOrigin, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImportOrigin), nil
	}
}

func (i importOriginDo) FindByPage(offset int, limit int) (result []*model.ImportOrigin, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i importOriginDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i importOriginDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i importOriginDo) Delete(models ...*model.ImportOrigin) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *importOriginDo) withDO(do gen.Dao) *importOriginDo {
	i.DO = *do.(*gen.DO)
	return i
}
