// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/adeynack/finances/model"
)

func newRegister(db *gorm.DB, opts ...gen.DOOption) register {
	_register := register{}

	_register.registerDo.UseDB(db, opts...)
	_register.registerDo.UseModel(&model.Register{})

	tableName := _register.registerDo.TableName()
	_register.ALL = field.NewAsterisk(tableName)
	_register.ID = field.NewString(tableName, "id")
	_register.CreatedAt = field.NewField(tableName, "created_at")
	_register.UpdatedAt = field.NewField(tableName, "updated_at")
	_register.Name = field.NewString(tableName, "name")
	_register.Type = field.NewString(tableName, "type")
	_register.BookID = field.NewString(tableName, "book_id")
	_register.ParentID = field.NewString(tableName, "parent_id")
	_register.StartsAt = field.NewField(tableName, "starts_at")
	_register.ExpiresAt = field.NewField(tableName, "expires_at")
	_register.CurrentcyIsoCode = field.NewString(tableName, "currentcy_iso_code")
	_register.Notes = field.NewString(tableName, "notes")
	_register.InitialBalance = field.NewInt64(tableName, "initial_balance")
	_register.Active = field.NewBool(tableName, "active")
	_register.DefaultCategoryID = field.NewString(tableName, "default_category_id")
	_register.InstitutionName = field.NewString(tableName, "institution_name")
	_register.AccountNumber = field.NewString(tableName, "account_number")
	_register.AnnualInterestRate = field.NewFloat32(tableName, "annual_interest_rate")
	_register.CreditLimit = field.NewInt64(tableName, "credit_limit")
	_register.CardNumber = field.NewString(tableName, "card_number")
	_register.ImportOrigins = registerHasManyImportOrigins{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ImportOrigins", "model.ImportOrigin"),
	}

	_register.Book = registerBelongsToBook{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Book", "model.Book"),
		Owner: struct {
			field.RelationField
			Books struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Book.Owner", "model.User"),
			Books: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Book.Owner.Books", "model.Book"),
			},
		},
		ImportOrigins: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Book.ImportOrigins", "model.ImportOrigin"),
		},
	}

	_register.Parent = registerBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "model.Register"),
		Book: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Parent.Book", "model.Book"),
		},
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Parent.Parent", "model.Register"),
		},
		DefaultCategory: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Parent.DefaultCategory", "model.Register"),
		},
		ImportOrigins: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Parent.ImportOrigins", "model.ImportOrigin"),
		},
	}

	_register.DefaultCategory = registerBelongsToDefaultCategory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("DefaultCategory", "model.Register"),
	}

	_register.fillFieldMap()

	return _register
}

type register struct {
	registerDo

	ALL                field.Asterisk
	ID                 field.String
	CreatedAt          field.Field
	UpdatedAt          field.Field
	Name               field.String
	Type               field.String
	BookID             field.String
	ParentID           field.String
	StartsAt           field.Field
	ExpiresAt          field.Field
	CurrentcyIsoCode   field.String
	Notes              field.String
	InitialBalance     field.Int64
	Active             field.Bool
	DefaultCategoryID  field.String
	InstitutionName    field.String
	AccountNumber      field.String
	AnnualInterestRate field.Float32
	CreditLimit        field.Int64
	CardNumber         field.String
	ImportOrigins      registerHasManyImportOrigins

	Book registerBelongsToBook

	Parent registerBelongsToParent

	DefaultCategory registerBelongsToDefaultCategory

	fieldMap map[string]field.Expr
}

func (r register) Table(newTableName string) *register {
	r.registerDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r register) As(alias string) *register {
	r.registerDo.DO = *(r.registerDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *register) updateTableName(table string) *register {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.CreatedAt = field.NewField(table, "created_at")
	r.UpdatedAt = field.NewField(table, "updated_at")
	r.Name = field.NewString(table, "name")
	r.Type = field.NewString(table, "type")
	r.BookID = field.NewString(table, "book_id")
	r.ParentID = field.NewString(table, "parent_id")
	r.StartsAt = field.NewField(table, "starts_at")
	r.ExpiresAt = field.NewField(table, "expires_at")
	r.CurrentcyIsoCode = field.NewString(table, "currentcy_iso_code")
	r.Notes = field.NewString(table, "notes")
	r.InitialBalance = field.NewInt64(table, "initial_balance")
	r.Active = field.NewBool(table, "active")
	r.DefaultCategoryID = field.NewString(table, "default_category_id")
	r.InstitutionName = field.NewString(table, "institution_name")
	r.AccountNumber = field.NewString(table, "account_number")
	r.AnnualInterestRate = field.NewFloat32(table, "annual_interest_rate")
	r.CreditLimit = field.NewInt64(table, "credit_limit")
	r.CardNumber = field.NewString(table, "card_number")

	r.fillFieldMap()

	return r
}

func (r *register) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *register) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 23)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["name"] = r.Name
	r.fieldMap["type"] = r.Type
	r.fieldMap["book_id"] = r.BookID
	r.fieldMap["parent_id"] = r.ParentID
	r.fieldMap["starts_at"] = r.StartsAt
	r.fieldMap["expires_at"] = r.ExpiresAt
	r.fieldMap["currentcy_iso_code"] = r.CurrentcyIsoCode
	r.fieldMap["notes"] = r.Notes
	r.fieldMap["initial_balance"] = r.InitialBalance
	r.fieldMap["active"] = r.Active
	r.fieldMap["default_category_id"] = r.DefaultCategoryID
	r.fieldMap["institution_name"] = r.InstitutionName
	r.fieldMap["account_number"] = r.AccountNumber
	r.fieldMap["annual_interest_rate"] = r.AnnualInterestRate
	r.fieldMap["credit_limit"] = r.CreditLimit
	r.fieldMap["card_number"] = r.CardNumber

}

func (r register) clone(db *gorm.DB) register {
	r.registerDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r register) replaceDB(db *gorm.DB) register {
	r.registerDo.ReplaceDB(db)
	return r
}

type registerHasManyImportOrigins struct {
	db *gorm.DB

	field.RelationField
}

func (a registerHasManyImportOrigins) Where(conds ...field.Expr) *registerHasManyImportOrigins {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a registerHasManyImportOrigins) WithContext(ctx context.Context) *registerHasManyImportOrigins {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a registerHasManyImportOrigins) Session(session *gorm.Session) *registerHasManyImportOrigins {
	a.db = a.db.Session(session)
	return &a
}

func (a registerHasManyImportOrigins) Model(m *model.Register) *registerHasManyImportOriginsTx {
	return &registerHasManyImportOriginsTx{a.db.Model(m).Association(a.Name())}
}

type registerHasManyImportOriginsTx struct{ tx *gorm.Association }

func (a registerHasManyImportOriginsTx) Find() (result []*model.ImportOrigin, err error) {
	return result, a.tx.Find(&result)
}

func (a registerHasManyImportOriginsTx) Append(values ...*model.ImportOrigin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a registerHasManyImportOriginsTx) Replace(values ...*model.ImportOrigin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a registerHasManyImportOriginsTx) Delete(values ...*model.ImportOrigin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a registerHasManyImportOriginsTx) Clear() error {
	return a.tx.Clear()
}

func (a registerHasManyImportOriginsTx) Count() int64 {
	return a.tx.Count()
}

type registerBelongsToBook struct {
	db *gorm.DB

	field.RelationField

	Owner struct {
		field.RelationField
		Books struct {
			field.RelationField
		}
	}
	ImportOrigins struct {
		field.RelationField
	}
}

func (a registerBelongsToBook) Where(conds ...field.Expr) *registerBelongsToBook {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a registerBelongsToBook) WithContext(ctx context.Context) *registerBelongsToBook {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a registerBelongsToBook) Session(session *gorm.Session) *registerBelongsToBook {
	a.db = a.db.Session(session)
	return &a
}

func (a registerBelongsToBook) Model(m *model.Register) *registerBelongsToBookTx {
	return &registerBelongsToBookTx{a.db.Model(m).Association(a.Name())}
}

type registerBelongsToBookTx struct{ tx *gorm.Association }

func (a registerBelongsToBookTx) Find() (result *model.Book, err error) {
	return result, a.tx.Find(&result)
}

func (a registerBelongsToBookTx) Append(values ...*model.Book) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a registerBelongsToBookTx) Replace(values ...*model.Book) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a registerBelongsToBookTx) Delete(values ...*model.Book) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a registerBelongsToBookTx) Clear() error {
	return a.tx.Clear()
}

func (a registerBelongsToBookTx) Count() int64 {
	return a.tx.Count()
}

type registerBelongsToParent struct {
	db *gorm.DB

	field.RelationField

	Book struct {
		field.RelationField
	}
	Parent struct {
		field.RelationField
	}
	DefaultCategory struct {
		field.RelationField
	}
	ImportOrigins struct {
		field.RelationField
	}
}

func (a registerBelongsToParent) Where(conds ...field.Expr) *registerBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a registerBelongsToParent) WithContext(ctx context.Context) *registerBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a registerBelongsToParent) Session(session *gorm.Session) *registerBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a registerBelongsToParent) Model(m *model.Register) *registerBelongsToParentTx {
	return &registerBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

type registerBelongsToParentTx struct{ tx *gorm.Association }

func (a registerBelongsToParentTx) Find() (result *model.Register, err error) {
	return result, a.tx.Find(&result)
}

func (a registerBelongsToParentTx) Append(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a registerBelongsToParentTx) Replace(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a registerBelongsToParentTx) Delete(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a registerBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a registerBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

type registerBelongsToDefaultCategory struct {
	db *gorm.DB

	field.RelationField
}

func (a registerBelongsToDefaultCategory) Where(conds ...field.Expr) *registerBelongsToDefaultCategory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a registerBelongsToDefaultCategory) WithContext(ctx context.Context) *registerBelongsToDefaultCategory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a registerBelongsToDefaultCategory) Session(session *gorm.Session) *registerBelongsToDefaultCategory {
	a.db = a.db.Session(session)
	return &a
}

func (a registerBelongsToDefaultCategory) Model(m *model.Register) *registerBelongsToDefaultCategoryTx {
	return &registerBelongsToDefaultCategoryTx{a.db.Model(m).Association(a.Name())}
}

type registerBelongsToDefaultCategoryTx struct{ tx *gorm.Association }

func (a registerBelongsToDefaultCategoryTx) Find() (result *model.Register, err error) {
	return result, a.tx.Find(&result)
}

func (a registerBelongsToDefaultCategoryTx) Append(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a registerBelongsToDefaultCategoryTx) Replace(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a registerBelongsToDefaultCategoryTx) Delete(values ...*model.Register) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a registerBelongsToDefaultCategoryTx) Clear() error {
	return a.tx.Clear()
}

func (a registerBelongsToDefaultCategoryTx) Count() int64 {
	return a.tx.Count()
}

type registerDo struct{ gen.DO }

func (r registerDo) Debug() *registerDo {
	return r.withDO(r.DO.Debug())
}

func (r registerDo) WithContext(ctx context.Context) *registerDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r registerDo) ReadDB() *registerDo {
	return r.Clauses(dbresolver.Read)
}

func (r registerDo) WriteDB() *registerDo {
	return r.Clauses(dbresolver.Write)
}

func (r registerDo) Session(config *gorm.Session) *registerDo {
	return r.withDO(r.DO.Session(config))
}

func (r registerDo) Clauses(conds ...clause.Expression) *registerDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r registerDo) Returning(value interface{}, columns ...string) *registerDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r registerDo) Not(conds ...gen.Condition) *registerDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r registerDo) Or(conds ...gen.Condition) *registerDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r registerDo) Select(conds ...field.Expr) *registerDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r registerDo) Where(conds ...gen.Condition) *registerDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r registerDo) Order(conds ...field.Expr) *registerDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r registerDo) Distinct(cols ...field.Expr) *registerDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r registerDo) Omit(cols ...field.Expr) *registerDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r registerDo) Join(table schema.Tabler, on ...field.Expr) *registerDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r registerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *registerDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r registerDo) RightJoin(table schema.Tabler, on ...field.Expr) *registerDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r registerDo) Group(cols ...field.Expr) *registerDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r registerDo) Having(conds ...gen.Condition) *registerDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r registerDo) Limit(limit int) *registerDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r registerDo) Offset(offset int) *registerDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r registerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *registerDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r registerDo) Unscoped() *registerDo {
	return r.withDO(r.DO.Unscoped())
}

func (r registerDo) Create(values ...*model.Register) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r registerDo) CreateInBatches(values []*model.Register, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r registerDo) Save(values ...*model.Register) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r registerDo) First() (*model.Register, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Register), nil
	}
}

func (r registerDo) Take() (*model.Register, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Register), nil
	}
}

func (r registerDo) Last() (*model.Register, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Register), nil
	}
}

func (r registerDo) Find() ([]*model.Register, error) {
	result, err := r.DO.Find()
	return result.([]*model.Register), err
}

func (r registerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Register, err error) {
	buf := make([]*model.Register, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r registerDo) FindInBatches(result *[]*model.Register, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r registerDo) Attrs(attrs ...field.AssignExpr) *registerDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r registerDo) Assign(attrs ...field.AssignExpr) *registerDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r registerDo) Joins(fields ...field.RelationField) *registerDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r registerDo) Preload(fields ...field.RelationField) *registerDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r registerDo) FirstOrInit() (*model.Register, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Register), nil
	}
}

func (r registerDo) FirstOrCreate() (*model.Register, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Register), nil
	}
}

func (r registerDo) FindByPage(offset int, limit int) (result []*model.Register, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r registerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r registerDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r registerDo) Delete(models ...*model.Register) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *registerDo) withDO(do gen.Dao) *registerDo {
	r.DO = *do.(*gen.DO)
	return r
}
